# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audioplayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 605)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.199, y1:0.772, x2:1, y2:0, stop:0 rgba(98, 19, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 10px;\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add = QtWidgets.QToolButton(self.centralwidget)
        self.add.setEnabled(True)
        self.add.setGeometry(QtCore.QRect(550, 20, 71, 71))
        self.add.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ic_fluent_add_square_24_filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon)
        self.add.setIconSize(QtCore.QSize(64, 64))
        self.add.setObjectName("add")
        self.musicList = QtWidgets.QListWidget(self.centralwidget)
        self.musicList.setGeometry(QtCore.QRect(15, 11, 511, 541))
        self.musicList.setStyleSheet("border: 10px;\n"
"border-radius: 10px;")
        self.musicList.setObjectName("musicList")
        self.recordPlayer = QtWidgets.QWidget(self.centralwidget)
        self.recordPlayer.setEnabled(True)
        self.recordPlayer.setGeometry(QtCore.QRect(150, 150, 451, 301))
        self.recordPlayer.setStyleSheet("border: 5px solid;\n"
"border-color: rgba(98, 19, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:reflect, x1:0.199, y1:0.772, x2:1, y2:0, stop:0 rgba(98, 19, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.recordPlayer.setObjectName("recordPlayer")
        self.prev = QtWidgets.QToolButton(self.recordPlayer)
        self.prev.setGeometry(QtCore.QRect(70, 220, 61, 61))
        self.prev.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.prev.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ic_fluent_previous_24_filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev.setIcon(icon1)
        self.prev.setIconSize(QtCore.QSize(48, 48))
        self.prev.setObjectName("prev")
        self.play = QtWidgets.QToolButton(self.recordPlayer)
        self.play.setGeometry(QtCore.QRect(150, 220, 61, 61))
        self.play.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ic_fluent_play_24_filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon2)
        self.play.setIconSize(QtCore.QSize(48, 48))
        self.play.setObjectName("play")
        self.stop = QtWidgets.QToolButton(self.recordPlayer)
        self.stop.setGeometry(QtCore.QRect(220, 220, 61, 61))
        self.stop.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.stop.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ic_fluent_stop_24_filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon3)
        self.stop.setIconSize(QtCore.QSize(48, 48))
        self.stop.setObjectName("stop")
        self.next = QtWidgets.QToolButton(self.recordPlayer)
        self.next.setGeometry(QtCore.QRect(300, 220, 61, 61))
        self.next.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.next.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ic_fluent_next_24_filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon4)
        self.next.setIconSize(QtCore.QSize(48, 48))
        self.next.setObjectName("next")
        self.temporaryTrack = QtWidgets.QSlider(self.recordPlayer)
        self.temporaryTrack.setGeometry(QtCore.QRect(70, 170, 291, 21))
        self.temporaryTrack.setStyleSheet("border: None;\n"
"background-color: rgb(0, 0, 0);")
        self.temporaryTrack.setOrientation(QtCore.Qt.Horizontal)
        self.temporaryTrack.setObjectName("temporaryTrack")
        self.audioVolume = QtWidgets.QSlider(self.recordPlayer)
        self.audioVolume.setGeometry(QtCore.QRect(400, 120, 31, 160))
        self.audioVolume.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: None;")
        self.audioVolume.setMaximum(100)
        self.audioVolume.setPageStep(5)
        self.audioVolume.setProperty("value", 10)
        self.audioVolume.setOrientation(QtCore.Qt.Vertical)
        self.audioVolume.setObjectName("audioVolume")
        self.musicCover = QtWidgets.QLabel(self.recordPlayer)
        self.musicCover.setGeometry(QtCore.QRect(40, 30, 81, 81))
        self.musicCover.setStyleSheet("border: None;")
        self.musicCover.setText("")
        self.musicCover.setObjectName("musicCover")
        self.musicName = QtWidgets.QLabel(self.recordPlayer)
        self.musicName.setGeometry(QtCore.QRect(130, 50, 281, 41))
        self.musicName.setStyleSheet("border: None;")
        self.musicName.setText("")
        self.musicName.setObjectName("musicName")
        self.closeWidget = QtWidgets.QToolButton(self.recordPlayer)
        self.closeWidget.setGeometry(QtCore.QRect(410, 10, 31, 31))
        self.closeWidget.setStyleSheet("border: None;\n"
"background-color: rgb(0, 0, 0);")
        self.closeWidget.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:/vscode/vscodeProjects/sejkesrj/Design/ic_fluent_pane_close_24_filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeWidget.setIcon(icon5)
        self.closeWidget.setIconSize(QtCore.QSize(32, 32))
        self.closeWidget.setObjectName("closeWidget")
        self.timer = QtWidgets.QLCDNumber(self.recordPlayer)
        self.timer.setGeometry(QtCore.QRect(160, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.timer.setFont(font)
        self.timer.setStyleSheet("border: None;\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.timer.setObjectName("timer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Astrum Audioplayer"))
